Added some error handling thoughts to the outline.  Implemented lots of error handling.  Changed some output lines.  Replumbed a clumsy pipeline to make more sense.

diff --git a/onlined b/onlined
--- a/onlined
+++ b/onlined
@@ -9,15 +9,26 @@ self_name="$(sed 's/^.*\///g' <<< "${0}")"
 
 
 function main {
+  timestamp
+
   while true; do
-    date --iso-8601=sec
     if check_online; then
-      output "Online!"
+      timestamp
+      output "Status:  online."
     else
-      refresh
+      while true; do 
+        timestamp
+        output "Status:  offline."
+        if refresh; then break; fi
+      done
     fi
     sleep "${sleep_secs}"
   done
+}
+
+
+function timestamp {
+  output "$(date --iso-8601=sec)"
 }
 
 
@@ -26,12 +37,22 @@ function output {
 }
 
 
+function error {
+  printf "%s:  ERROR:  %s\n" "${self_name}" "${1}" >&2
+}
+
+
+function warn {
+  printf "%s:  WARNING :  %s\n" "${self_name}" "${1}" >&2
+}
+
+
 function refresh {
   output "Refreshing."
   read -a interfaces <<< $(get_interfaces)
   read -a spec_names <<< $(get_spec_names)
 
-  ifdown "${interfaces[@]}"
+  ifdown "${interfaces[@]}" || error "Failed to bring down interfaces:  ( ${interfaces[@]} )"
 
   for spec_name in "${spec_names[@]}"; do
     for interface in "${interfaces[@]}"; do
@@ -41,11 +62,13 @@ function refresh {
           output "Successfully brought up interface:  ${interface}"
           return 0
         else
-          ifdown "${interface}"
+          #warn "Failed to bring up interface:  ${interface}"
+          ifdown "${interface}" || error "Failed to bring down interface:  ${wifi_interface}"
         fi
       fi
     done
   done
+  #warn "Failed to bring up any interface by name."
 
   wifi_names=()
   while read wifi_name; do
@@ -55,52 +78,60 @@ function refresh {
   for spec_name in "${spec_names[@]}"; do
     for wifi_name in "${wifi_names[@]}"; do
       if test "${spec_name}" == "${wifi_name}"; then
-        output "Trying network:  ${wifi_name}"
+        output "Trying wifi network:  ${wifi_name}"
         if ifup "${wifi_interface}=${spec_name}" && check_online; then
-          output "Successfully joined network:  ${wifi_name}"
+          output "Successfully joined wifi network:  ${wifi_name}"
           return 0
         else
-          ifdown "${wifi_interface}"
+          warn "Failed to join wifi network:  ${wifi_name}"
+          ifdown "${wifi_interface}" || error "Failed to bring down interface:  ${wifi_interface}"
         fi
       fi
     done
   done
 
-  output "Failed to refresh."
+  error "Failed to get online."
   return 1
 }
 
 
 function check_online_passive {
-  active_interface="$(get_active_interface)" \
-  || return 1
-  read -a range_bottom_dec_string range_top_dec_string <<< $(get_range $(get_address_and_mask "${active_interface}"))
+  if ! active_interface="$(get_active_interface)"; then
+    error "Failed to identify active interface."
+    return 1
+  fi
+
+  if ! address_and_mask="$(get_address_and_mask "${active_interface}")"; then
+    warn "Failed to get address and mask."
+  fi
+
+  if ! read -a range_bottom_dec_string range_top_dec_string <<< $(get_range ${address_and_mask}); then
+    error "Failed to identify address range of local subnet."
+    return 1
+  fi
+
   range_bottom_bin_string="$(address_dec_to_bin "${range_bottom_dec_string}")"
   range_top_bin_string="$(address_dec_to_bin "${range_top_dec_string}")"
 
-  # timeout makes sub-scope.  Make it return false on success, flip that value and return from the function.  This is stupid.
-  output "Sniffing traffic on ${active_interface} for inbound packets from off-subnet."
-  timeout "${sniff_secs}" tcpdump -i "${active_interface}" -n 2>~/tmp/errors.txt \
-  | grep -E '[^ ]+[[:space:]]+IP' \
-  | while read time IP src_address_dot_port arrow dst_address_dot_port garbage; do 
+  output "Watching ${active_interface} for ${sniff_secs}s for inbound internet traffic."
 
+  while read time IP src_address_dot_port arrow dst_address_dot_port garbage; do 
     src_address_dec_string="$(sed 's/\.[0-9]*$//' <<< "${src_address_dot_port}")"
     dst_address_dec_string="$(sed -E 's/\.[0-9]*:$//' <<< "${dst_address_dot_port}")"
     src_address_bin_string="$(address_dec_to_bin "${src_address_dec_string}")"
     dst_address_bin_string="$(address_dec_to_bin "${dst_address_dec_string}")"
 
     if test "$((2#$src_address_bin_string))" -lt "$((2#$range_bottom_bin_string))"; then
-      return 1
+      return 0
+    elif test "$((2#$src_address_bin_string))" -gt "$((2#$range_top_bin_string))"; then
+      return 0
     fi
-    if test "$((2#$src_address_bin_string))" -gt "$((2#$range_top_bin_string))"; then
-      return 1
-    fi
-  done
-  if test $? -eq 0; then
-    return 1
-  else
-    return 0
-  fi
+  done < <(
+    timeout "${sniff_secs}" tcpdump -i "${active_interface}" -n \
+    | grep -E '[^ ]+[[:space:]]+IP' \
+  )
+
+  return 1
 }
 
 
@@ -122,7 +153,12 @@ function bin_to_dec {
 
 
 function get_active_interface {
-  ip route | awk '/default/ {print $5}' | grep .
+  if ! route_list="$(ip route)"; then
+    error "Failed to list routes."
+    return 1
+  fi
+  route_list="$(awk '/default/ {print $5}' <<< "${route_list}")"
+  grep . <<< "${route_list}"
 }
 
 
@@ -132,24 +168,50 @@ function get_interfaces {
     skip_interfaces_regex+="${interface}|"
   done
   skip_interfaces_regex="$(sed 's/|$//' <<< "${skip_interfaces_regex}")"
-  echo $(ip link | awk '/^[0-9]+: / {print $2}' | sed 's/:$//' | grep -Ev "^${skip_interfaces_regex}")
+  if ! interface_list="$(ip link)"; then
+    error "Failed to list interfaces."
+    return 1
+  fi
+  interface_list="$(awk '/^[0-9]+: / {print $2}' <<< "${interface_list}")"
+  interface_list="$(sed 's/:$//' <<< "${interface_list}")"
+  interface_list="$(grep -Ev "^${skip_interfaces_regex}" <<< "${interface_list}")"
+
+  # No quotes.
+  echo ${interface_list}
 }
 
 
 function get_spec_names {
-  echo $(awk '/iface/ {print $2}' /etc/network/interfaces{,.d/*})
+  if ! spec_list="$(cat /etc/network/interfaces{,.d/*})"; then
+    error "Failed to read network specification list(s)."
+    return 1
+  fi
+  spec_list="$(awk '/iface/ {print $2}' <<< "${spec_list}")"
+  # No quotes.
+  echo ${spec_list}
 }
 
 
 function get_wifi_names {
-  ip link set "${wifi_interface}" up
-  iwlist "${wifi_interface}" scan | awk -F '[:"]' '/^ *ESSID:/ {print $3}'
+  if ! ip link set "${wifi_interface}" up; then
+    warn "Failed to mark interface as up:  ${wifi_interface}"
+  fi
+
+  if ! wifi_list="$(iwlist "${wifi_interface}" scan)"; then
+    error "Failed to scan for wifi names."
+    return 1
+  fi
+  # Wifi names can have spaces; leave them on separate lines.
+  awk -F '[:"]' '/^ *ESSID:/ {print $3}' <<< "${wifi_list}"
 }
 
 
 function get_address_and_mask {
-    ip addr show dev "${1}" \
-    | awk '/^    inet / {print $2}' \
+    if ! address_and_mask="$(ip addr show dev "${1}")"; then
+      error "Failed to query address and mask."
+      return 1
+    fi
+    awk '/^    inet / {print $2}' <<< "${address_and_mask}" \
     | sed 's/\// /' \
     | awk '{print $1" "$2}'
 }
